### PR TITLE
add some gio overrides

### PR DESCRIPTION
**Pull request by jonath92**
This adds some overrides from gio which are based on: https://gitlab.gnome.org/GNOME/gjs/-/blob/master/modules/core/overrides/Gio.js. But not complete yet. 
There is actually a lot of interesting stuff in the `overrides` dir which should be ideally included in this repo.

### CODE REVIEW

**Comment by jonath92** [comment]
I also added now github actions. For that you once more need to add your npm secret as decribed here: https://github.com/Gr3q/types-cjs/pull/9#issue-1086975155

**Comment by Gr3q** [comment]
Please verify that they typings are correct with [CJS](https://github.com/linuxmint/cjs/tree/master/modules/core/overrides) instead, that's what Cinnamon is using

**Comment by Gr3q** [comment]
Also I'm thinking to just use a single package for cjs and move these to cjs because even these are becoming Cinnamon specific.

**Comment by jonath92** [comment]
> Please verify that they typings are correct with CJS instead, that's what Cinnamon is using

Ok yes that sound reasonable. Ths cjs and gjs versions are mostly the same and the changes in this pr are valid for both

> Also I'm thinking to just use a single package for cjs and move these to cjs because even these are becoming Cinnamon specific.

Yes I agree with that. It is also easier to make changes that way. Currently I sometimes have to make changes in 3 repos at the same time - in the applets, cjs and gjs. 
 
The only problem of this pr is the github action which I will remove in a second. Aftwards you can imo merge this pr and thereupon move all of this repo to the cjs repo.

**Review by Gr3q — APPROVED** [review]

**Pull request merged**
